### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by bleckley** [jpuigcerver/xer#1]
Thanks for this great code. I am trying it out for the first time and getting a syntax error on the "str" element of the example provided. Any guidance you can provide would be greatly appreciated.
Thanks again!

**Comment by jpuigcerver** [comment]
Can you be more specific on the error? In any case, if I had to guess, given that this program is super old, I would say it probably doesn't play well together with Python 3.

**Comment by bleckley** [comment]
Thank you for your response. Here's the issue I ran into:
```
import xer

xer -i str -r "I'm André" -t "I'm Andrew"
  File "<ipython-input-2-e20c4406a634>", line 1
    xer -i str -r "I'm André" -t "I'm Andrew"
             ^
SyntaxError: invalid syntax
```

**Comment by jpuigcerver** [comment]
Wait a second, are you trying to run `xer -i str -r "I'm André" -t "I'm Andrew"` from the Python interpreter? 

That should be run from the command line (a.k.a. Linux/Mac terminal).

**Comment by bleckley** [comment]
Thanks for your help with this.
